version: "3"
services:
  springapp:
    image: darraghwalker/passengerspring
    container_name: passengerspring
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
    ports:
      - 8000:8080
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: