version: "3"
services:
  springapp:
    image: darraghwalker/passengerspring
    container_name: passengerspring
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
    ports:
      - 8000:8080
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: